#### SQLite
> Explorer    
  ㅣ    
  DB    
  ㄴ Data    
  ㄴ Note - Database.ipynb

In [ ]:
import sqlite3 # sqlite는 관리용 (퍼포먼스 빠름), 서비스용은 아님

# sqlite 데이터베이스 연결하기
dbPath = "../Data/test.sqlite"
conn = sqlite3.connect(dbPath) # connect는 연결 역할

# 테이블을 생성하고 데이터 넣기
curs = conn.cursor() # 데이터베이스 작업을 하려면 cursor 필요
curs.executescript(  # excute = 한줄, executescript = 여러줄
    """ 
    DROP TABLE IF EXISTS items;
    CREATE TABLE items(
        item_id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT,
        price INTEGER
    );
    """ # 줄이 끝나는 위치에 ;
)

# 위의 조작을 데이터베이스에 반영하기
conn.commit()

In [ ]:
# 데이터 넣기
curs = conn.cursor()
curs.execute(
    "INSERT INTO items (name, price) VALUES (?,?)", # 테이블의 한 줄을 레코드 혹은 튜플이라고 한다.
    ("Orange", 5200)                                # 따라서 데이터를 튜플로 넣어준다.
)
conn.commit()

In [3]:
# 여러 데이터 연속으로 넣기
curs = conn.cursor()
data = [("Mango", 7700), ("Kiwi", 4000), ("Grape", 8700), ("Peach", 9400)]
curs.executemany(   # 반복문 역할
    "INSERT INTO items (name, price) VALUES (?,?)",
    data
)
conn.commit()

In [6]:
# 데이터 추출하기
curs = conn.cursor()
curs.execute(
    "SELECT item_id, name, price FROM items"
)
item_list = curs.fetchall() # 리스트 가져오기
item_list
# for item in item_list:
#     print(item)

[(1, 'Orange', 5200),
 (2, 'Mango', 7700),
 (3, 'Kiwi', 4000),
 (4, 'Grape', 8700),
 (5, 'Peach', 9400)]

In [ ]:
# 4000원 ~ 7000원 사이의 데이터 추출하기
curs = conn.cursor()
curs.execute(
    "SELECT * FROM items WHERE price BETWEEN ? AND ?",
    (4000, 7000)    # [] , () 상관 없음 - 데이터베이스는 구분 못함
)
item_list = curs.fetchall()
item_list

[(1, 'Orange', 5200), (3, 'Kiwi', 4000)]

----
### MySQL

In [14]:
# !pip install pymysql # 해당 install 실행

In [ ]:
import pymysql

# MySQL Connection
conn = pymysql.connect(
    host='192.168.20.52', # 본인 IPv4 주소 (LAN, 이더넷 x) -> cmd에서 ipconfig 입력
    user='root',
    password='qwer1234',
    database='education', # MySQL Workbench에 있는 schemas
    charset='utf8'
)

# Connection으로 부터 Cursor 생성
curs = conn.cursor()

In [ ]:
# SQL 문장
sql = "SELECT * FROM student" # 위에서 education으로 정했기때문에 table만 적으면 된다.
curs.execute(sql)
rows = curs.fetchall()
print(rows)
conn.close() # 연결 끊어주기 (반드시 끊어줘야 다른 사람들도 데이터베이스 이용 가능)

(('b002', '관우', '심리학과', '010-222', '서울'), ('b003', '장비', '경제학과', '010-333', '서울'), ('c002', '여포', '심리학과', '016-222', '경기'), ('c003', '손견', '경제학과', '016-333', '경기'), ('d001', '홍길동', '수학과', '017-111', '광주'), ('S001', '박소명', '컴퓨터공학과', '123-4567', None), ('S002', '최민국', '컴퓨터공학과', '234-5678', None), ('S005', '김상진', '사학과', '567-8901', None), ('S006', '황정숙', '사학과', '678-9012', None))

In [17]:
rowList = list(rows)
print(rowList)

[('b002', '관우', '심리학과', '010-222', '서울'), ('b003', '장비', '경제학과', '010-333', '서울'), ('c002', '여포', '심리학과', '016-222', '경기'), ('c003', '손견', '경제학과', '016-333', '경기'), ('d001', '홍길동', '수학과', '017-111', '광주'), ('S001', '박소명', '컴퓨터공학과', '123-4567', None), ('S002', '최민국', '컴퓨터공학과', '234-5678', None), ('S005', '김상진', '사학과', '567-8901', None), ('S006', '황정숙', '사학과', '678-9012', None)]

In [19]:
print(rowList[0])
print(rowList[0][1])

('b002', '관우', '심리학과', '010-222', '서울')
관우

- 데스크톱 서버는 데스크톱끼리만 연결 가능 노트북 서버는 노트북끼리만 연결 가능.
- 데스크톱을 서버로 쓰게 되면 노트북에선 젠더를 연결 시켜줘야 연결 가능.

---
#### Insert Data

In [36]:
conn = pymysql.connect(
    host='192.168.20.52', # 본인 IPv4 주소 (LAN, 이더넷 x) -> cmd에서 ipconfig 입력
    user='root',
    password='qwer1234',
    database='education', # MySQL Workbench에 있는 schemas
    charset='utf8'
)
# close 후에는 반드시 connect를 다시 해줘야함. 나중엔 함수로 만들어 사용하는게 편리

curs = conn.cursor()

In [37]:
# sql 문장
sql = """
        INSERT INTO student(scode, sname, sdept, sphone, saddress)
        VALUES (%s,%s,%s,%s,%s)
    """

In [38]:
curs.execute(sql, ('a002', '유비', '건축학과', '010-1111', '서울'))

1

In [39]:
conn.commit()

In [40]:
# SQL 문장
sql = "SELECT * FROM student"
curs.execute(sql)
rows = curs.fetchall()
print(rows)
conn.close()

(('a001', '관우', '심리학과', '010-2222', '서울'), ('a002', '유비', '건축학과', '010-1111', '서울'), ('b002', '관우', '심리학과', '010-222', '서울'), ('b003', '장비', '경제학과', '010-333', '서울'), ('c002', '여포', '심리학과', '016-222', '경기'), ('c003', '손견', '경제학과', '016-333', '경기'), ('d001', '홍길동', '수학과', '017-111', '광주'), ('S001', '박소명', '컴퓨터공학과', '123-4567', None), ('S002', '최민국', '컴퓨터공학과', '234-5678', None), ('S005', '김상진', '사학과', '567-8901', None), ('S006', '황정숙', '사학과', '678-9012', None))

---
#### Insert many Data

In [41]:
conn = pymysql.connect(
    host='192.168.20.52', # 본인 IPv4 주소 (LAN, 이더넷 x) -> cmd에서 ipconfig 입력
    user='root',
    password='qwer1234',
    database='education', # MySQL Workbench에 있는 schemas
    charset='utf8'
)
# close 후에는 반드시 connect를 다시 해줘야함. 나중엔 함수로 만들어 사용하는게 편리

curs = conn.cursor()

In [43]:
data = (
    ('x001', '조조', '국문학과', '016-1111', '경기'),
    ('x002', '여포', '심리학과', '016-2222', '경기'),
    ('x003', '동탁', '경제학과', '016-3333', '경기')
)

In [44]:
# sql 문장
sql = """
        INSERT INTO student(scode, sname, sdept, sphone, saddress)
        VALUES (%s,%s,%s,%s,%s)
    """

In [ ]:
curs.executemany(sql, data)
conn.commit()

In [49]:
# SQL 문장
sql = "SELECT * FROM student"
curs.execute(sql)
rows = curs.fetchall()
print(rows)
conn.close()

(('a001', '관우', '심리학과', '010-2222', '서울'), ('a002', '유비', '건축학과', '010-1111', '서울'), ('b002', '관우', '심리학과', '010-222', '서울'), ('b003', '장비', '경제학과', '010-333', '서울'), ('c002', '여포', '심리학과', '016-222', '경기'), ('c003', '손견', '경제학과', '016-333', '경기'), ('d001', '홍길동', '수학과', '017-111', '광주'), ('S001', '박소명', '컴퓨터공학과', '123-4567', None), ('S002', '최민국', '컴퓨터공학과', '234-5678', None), ('S005', '김상진', '사학과', '567-8901', None), ('S006', '황정숙', '사학과', '678-9012', None), ('x001', '조조', '국문학과', '016-1111', '경기'), ('x002', '여포', '심리학과', '016-2222', '경기'), ('x003', '동탁', '경제학과', '016-3333', '경기'))

----
#### select의 내용을 dataframe으로 보기

In [55]:
# !pip install sqlalchemy # sqlalchemy 다운 (이미 다운되어있을 수 있음)

In [51]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("mysql+pymysql://root:qwer1234@192.168.20.52:3306/education")
# (연결할 데이터베이스 종류+파이썬 드라이버://아이디:비밀번호@본인IPv4주소:port번호/schemas)

In [53]:
from sqlalchemy.sql import text
sql = """
    SELECT * FROM student;
"""

with engine.connect() as conn:
    query = conn.execute(text(sql))

df = pd.DataFrame(query.fetchall())
df

   scode sname   sdept    sphone saddress
0   a001    관우    심리학과  010-2222       서울
1   a002    유비    건축학과  010-1111       서울
2   b002    관우    심리학과   010-222       서울
3   b003    장비    경제학과   010-333       서울
4   c002    여포    심리학과   016-222       경기
5   c003    손견    경제학과   016-333       경기
6   d001   홍길동     수학과   017-111       광주
7   S001   박소명  컴퓨터공학과  123-4567      NaN
8   S002   최민국  컴퓨터공학과  234-5678      NaN
9   S005   김상진     사학과  567-8901      NaN
10  S006   황정숙     사학과  678-9012      NaN
11  x001    조조    국문학과  016-1111       경기
12  x002    여포    심리학과  016-2222       경기
13  x003    동탁    경제학과  016-3333       경기

In [54]:
conn.close()

---
#### dataframe을 Database로 Insert하기

In [ ]:
poem = pd.read_csv("../Data/윤동주.csv") # 파일 읽기
poem.columns = ['seq', 'title'] # columns 이름 변경
poem.head() # 파일 확인

   seq         title
0    0  하늘과 바람과 별과 시
1    1            서시
2    2           자화상
3    3            소년
4    4       눈 오는 지도

In [58]:
engine = create_engine("mysql+pymysql://root:qwer1234@192.168.20.52:3306/poem")
conn = engine.connect()

In [ ]:
poem.to_sql(
    name='poemtable',   # table 이름
    con=engine,         # 연결
    if_exists='append', # 추가
    index=False         # index 번호는 빼고
)

94

In [60]:
conn.close()

---
#### TinyDB
- NoSQL 문서형 데이터베이스
- MongoDB가 대표적이다.

In [ ]:
# !pip install tinydb

Collecting tinydb
  Downloading tinydb-4.9.0-py3-none-any.whl.metadata (6.7 kB)
Downloading tinydb-4.9.0-py3-none-any.whl (25 kB)
Installing collected packages: tinydb
Successfully installed tinydb-4.9.0

In [62]:
from tinydb import TinyDB, Query, where

# 데이터베이스 연결하기
filepath = "../Data/tinydb.json" # 문서형 데이터베이스는 모두 json 형식
db = TinyDB(filepath)

In [63]:
# 기존에 테이블이 있다면 제거하기
db.drop_table('fruits')

In [64]:
# 테이블 생성하기
table = db.table('fruits')

In [65]:
# 테이블에 데이터 추가하기
table.insert(
    {
        'name' : 'Banana',
        'price' : 6000
    }
)
table.insert(
    {
        'name' : 'Orange',
        'price' : 12000
    }
)
table.insert(
    {
        'name' : 'Mango',
        'price' : 7000
    }
)

3

In [66]:
# 모든 데이터 추출하기
print(table.all())

[{'name': 'Banana', 'price': 6000}, {'name': 'Orange', 'price': 12000}, {'name': 'Mango', 'price': 7000}]

In [72]:
# Orange 검색하기
item = Query()
res = table.search(item.name == 'Orange')
print(res)
print(f"orange is {res[0]['price']}.")

[{'name': 'Orange', 'price': 12000}]
orange is 12000.

In [75]:
# 가격이 8000이상인 것 추출하기
item = Query()
res = table.search(item.price >= 8000)
res

[{'name': 'Orange', 'price': 12000}]

In [76]:
# 수정하기
table.upsert({'price':8000}, item.name == "Mango")
res = table.search(item.name == "Mango")
res

[{'name': 'Mango', 'price': 8000}]